# Generated by Django 2.0.9 on 2018-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('boss', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=255)),
                ('addr', models.CharField(default='', max_length=255)),
                ('license', models.CharField(default='', max_length=255)),
                ('account', models.CharField(default='', max_length=255)),
                ('pwd', models.CharField(default='', max_length=255)),
                ('regtime', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('oldpri', models.CharField(default='', max_length=255)),
                ('newpri', models.CharField(default='', max_length=255)),
                ('standard', models.CharField(default='', max_length=255)),
                ('place', models.CharField(default='', max_length=255)),
                ('store', models.CharField(default='', max_length=255)),
                ('aftersale', models.CharField(default='', max_length=255)),
                ('paras', models.CharField(default='', max_length=255)),
                ('detail', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('addtime', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
