# Generated by Django 2.0.9 on 2018-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('property_name', models.CharField(default='', max_length=255)),
                ('property_manager', models.CharField(default='', max_length=255)),
                ('property_tel', models.CharField(default='', max_length=255)),
                ('community_name', models.CharField(default='', max_length=255)),
                ('community_addr', models.CharField(default='', max_length=255)),
                ('community_manager', models.CharField(default='', max_length=255)),
                ('community_manager_tel', models.CharField(default='', max_length=255)),
                ('community_start_time', models.CharField(default='', max_length=255)),
                ('community_home_num', models.CharField(default='', max_length=255)),
                ('community_account', models.CharField(default='', max_length=255)),
                ('community_pwd', models.CharField(default='', max_length=255)),
                ('reg_time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fno', models.CharField(default='', max_length=255)),
                ('fname', models.CharField(default='', max_length=255)),
                ('no', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=255)),
                ('pwd', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='siteusr',
        ),
    ]
