# Generated by Django 2.0.9 on 2018-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(default='', max_length=255)),
                ('building', models.CharField(default='', max_length=255)),
                ('unit', models.CharField(default='', max_length=255)),
                ('floor', models.CharField(default='', max_length=255)),
                ('room', models.CharField(default='', max_length=255)),
                ('owner_name', models.CharField(default='', max_length=255)),
                ('owner_tel', models.CharField(default='', max_length=255)),
                ('area', models.CharField(default='', max_length=255)),
                ('is_empty', models.CharField(default='', max_length=255)),
                ('is_lift', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('owner_id', models.CharField(default='', max_length=255)),
                ('addtime', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(default='', max_length=255)),
                ('house_id', models.CharField(default='', max_length=255)),
                ('fee_year', models.CharField(default='', max_length=255)),
                ('fee_month', models.CharField(default='', max_length=255)),
                ('fee_name', models.CharField(default='', max_length=255)),
                ('fee_type', models.CharField(default='', max_length=255)),
                ('fee_pri', models.CharField(default='', max_length=255)),
                ('fee_unit', models.CharField(default='', max_length=255)),
                ('fee_ratio', models.CharField(default='', max_length=255)),
                ('fee_amount', models.CharField(default='', max_length=255)),
                ('fee_money', models.CharField(default='', max_length=255)),
                ('fee_status', models.CharField(default='', max_length=255)),
                ('fee_online', models.CharField(default='', max_length=255)),
                ('addtime', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeeBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(default='', max_length=255)),
                ('fee_name', models.CharField(default='', max_length=255)),
                ('fee_type', models.CharField(default='', max_length=255)),
                ('fee_pri', models.CharField(default='', max_length=255)),
                ('fee_unit', models.CharField(default='', max_length=255)),
                ('fee_ratio', models.CharField(default='', max_length=255)),
                ('empty_fee_type', models.CharField(default='', max_length=255)),
                ('empty_fee_pri', models.CharField(default='', max_length=255)),
                ('empty_fee_unit', models.CharField(default='', max_length=255)),
                ('empty_fee_ratio', models.CharField(default='', max_length=255)),
                ('fee_period', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeePara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(default='', max_length=255)),
                ('fee_basic_id', models.CharField(default='', max_length=255)),
                ('fee_special_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeeSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(default='', max_length=255)),
                ('building', models.CharField(default='', max_length=255)),
                ('unit', models.CharField(default='', max_length=255)),
                ('floor', models.CharField(default='', max_length=255)),
                ('room', models.CharField(default='', max_length=255)),
                ('owner_name', models.CharField(default='', max_length=255)),
                ('fee_name', models.CharField(default='', max_length=255)),
                ('fee_type', models.CharField(default='', max_length=255)),
                ('fee_pri', models.CharField(default='', max_length=255)),
                ('fee_unit', models.CharField(default='', max_length=255)),
                ('fee_ratio', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
